export const CREATE_MATRIX = 'CREATE_MATRIX';
export const CHANGE_VALUE_M = 'CHANGE_VALUE_M';
export const CHANGE_VALUE_N = 'CHANGE_VALUE_N';
export const CHANGE_VALUE_X = 'CHANGE_VALUE_X';
export const EXECUTE_SUM_ROW = 'EXECUTE_SUM_ROW';
export const EXECUTE_AVERAGE_COL = 'EXECUTE_AVERAGE_COL';
export const COUNTER_MATRIX = 'COUNTER_MATRIX';
export const EXECUTE_COMING_ITEMS = 'EXECUTE_COMING_ITEMS';
export const CLEAR_STATE_MATRIX = 'CLEAR_STATE_MATRIX';
export const EXECUTE_PERCENT_ROW = 'EXECUTE_PERCENT_ROW';


